---

- name: Create a new database with name '{{ dbname }}'
  mysql_db:
    name: '{{ dbname }}'
    state: present
  when: ansible_facts['distribution'] == 'CentOS'

- name: Create database user with password and all database privileges and 'WITH GRANT OPTION'
  mysql_user:
    name: '{{ dbuser }}'
    password: '{{ dbpass }}'
    priv: '{{ dbname }}.*:ALL,GRANT'
    host: '%'
    state: present
  when: ansible_facts['distribution'] == 'CentOS'

...
